### ISSUE TITLE
Unable to Apply Wallpaper Setting

### ISSUE THREAD

**Issue by cprin21** [realmazharhussain/gdm-settings#111]
### What happened?

Applying the setting of a wallpaper does nothing.

### Expected behavior

The apply button should come up with a popup saying things might look weird until you log out, but this does not occur.
Quitting the app and restarting it shows that nothing has changed and the Background section is still set to None.

### To Reproduce

Click the Image dropdown to the right of Type in the Background section on the Appearance tab.
Click Image. Browse for a wallpaper and select it.
Click Apply. Optionally restart the app to show that nothing has changed.

### Detailed Explaination (Optional)

Receiving this message in terminal if running the flatpak through the terminal:
```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 130, in <lambda>
    self._finish_callback = lambda self, task, nothing: finish_callback()
  File "/app/lib/python3.9/site-packages/gdm_settings/window.py", line 121, in on_apply_finished
    if self.apply_task.finish():
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 160, in finish
    raise value
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 145, in _thread_cb
    retval = self._function()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 398, in apply_settings
    self.apply_shell_theme_settings()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 238, in apply_shell_theme_settings
    compiled_file = gr_utils.compile(shelldir,
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 98, in compile
    extract_default_theme(temp_theme_dir)
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 64, in extract_default_theme
    resource_list = getstdout(["gresource", "list", env.HOST_ROOT + gresource_file]).decode().splitlines()
TypeError: can only concatenate str (not "NoneType") to str
```

### Application Version

1.0

### Source

Flatpak

### Environment

- **OS**: 
- **GNOME**:

**Comment by realmazharhussain** [comment]
This issue is being discussed in #104.
