### ISSUE TITLE
Setting fail to apply gnome 43

### ISSUE THREAD

**Issue by hiikion** [realmazharhussain/gdm-settings#113]
### What happened?

When changing any setting and hitting apply it gives me this error in the console:
`
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 130, in <lambda>
    self._finish_callback = lambda self, task, nothing: finish_callback()
  File "/app/lib/python3.9/site-packages/gdm_settings/window.py", line 121, in on_apply_finished
    if self.apply_task.finish():
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 160, in finish
    raise value
  File "/app/lib/python3.9/site-packages/gdm_settings/utils.py", line 145, in _thread_cb
    retval = self._function()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 398, in apply_settings
    self.apply_shell_theme_settings()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings.py", line 238, in apply_shell_theme_settings
    compiled_file = gr_utils.compile(shelldir,
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 98, in compile
    extract_default_theme(temp_theme_dir)
  File "/app/lib/python3.9/site-packages/gdm_settings/gr_utils.py", line 64, in extract_default_theme
    resource_list = getstdout(["gresource", "list", env.HOST_ROOT + gresource_file]).decode().splitlines()
TypeError: can only concatenate str (not "NoneType") to str
`

### Expected behavior

application of settings 

### To Reproduce

Change any setting and hit apply 

### Application Version

v1.0

### Source

Flatpak

### Environment

- **OS**: Fedora 37
- **GNOME**: 43

**Comment by realmazharhussain** [comment]
This issue is being discussed in #104. Please provide feedback there.
