### ISSUE TITLE
Appimage crashes on startup using Fedora 37 (Gnome 43)

### ISSUE THREAD

**Issue by bramvanoploo** [realmazharhussain/gdm-settings#116]
### What happened?

Runninf the appimage results in an error. 
The flatpak version doesn't have this issue.

### Expected behavior

The application should start

### To Reproduce

Run the appimage from terminal in Fedora 37 to see the resulting error

### Detailed Explaination (Optional)

Running the appimage from terminal this is the result:

```
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
QSocketNotifier: Can only be used with threads started with QThread

** (process:14180): WARNING **: 10:52:49.268: Failed to load shared library 'libpango-1.0.so.0' referenced by the typelib: libbz2.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/tmp/.mount_Login_FgiKhx/usr/bin/gdm-settings", line 24, in <module>
    from gdm_settings import Application
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/site-packages/gdm_settings/__init__.py", line 1, in <module>
    from .app import Application
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 10, in <module>
    from gi.repository import Adw, Gtk
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/site-packages/gi/importer.py", line 150, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/site-packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/tmp/.mount_Login_FgiKhx/usr/lib/python3.10/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError
```

### Application Version

1.0

### Source

Appimage

### Environment

- **OS**: Fedora 37
- **GNOME**: 43

**Comment by realmazharhussain** [comment]
Try [this AppImage](https://fastupload.io/en/jCM88LMuobBXcY3/file).

**Comment by bramvanoploo** [comment]
> 

Same result... different error.

```
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
QSocketNotifier: Can only be used with threads started with QThread

** (process:7445): WARNING **: 12:05:41.149: Failed to load shared library 'libgdk_pixbuf-2.0.so.0' referenced by the typelib: libjpeg.so.8: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/tmp/.mount_gdm-seW9BsUG/usr/bin/gdm-settings", line 24, in <module>
    from gdm_settings import Application
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/site-packages/gdm_settings/__init__.py", line 1, in <module>
    from .app import Application
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 10, in <module>
    from gi.repository import Adw, Gtk
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/site-packages/gi/importer.py", line 150, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/site-packages/gi/overrides/GdkPixbuf.py", line 32, in <module>
    class Pixbuf(GdkPixbuf.Pixbuf):
  File "/tmp/.mount_gdm-seW9BsUG/usr/lib/python3.10/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError
```

**Comment by realmazharhussain** [comment]
What about [this one](https://fastupload.io/en/fb1SEHs3FfrFsYM/file)?

**Comment by bramvanoploo** [comment]
> What about [this one](https://fastupload.io/en/fb1SEHs3FfrFsYM/file)?

Yes. Now it's working :)
