### ISSUE TITLE
Unable to Apply settings in version 2.0  with Manjaro + Gnome 43.2 Wayland

### ISSUE THREAD

**Issue by MrPestle** [realmazharhussain/gdm-settings#141]
### What happened?

$ flatpak run io.github.realmazharhussain.GdmSettings            
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/gdm_settings/utils.py", line 131, in <lambda>
    finish_callback = lambda self, task, nothing: self.finish_callback()
  File "/app/lib/python3.10/site-packages/gdm_settings/window.py", line 135, in on_apply_finished
    if self.apply_task.finish():
  File "/app/lib/python3.10/site-packages/gdm_settings/utils.py", line 156, in finish
    raise value
  File "/app/lib/python3.10/site-packages/gdm_settings/utils.py", line 141, in _thread_cb
    retval = self.function()
  File "/app/lib/python3.10/site-packages/gdm_settings/settings.py", line 524, in apply_settings
    self.apply_shell_theme_settings()
  File "/app/lib/python3.10/site-packages/gdm_settings/settings.py", line 340, in apply_shell_theme_settings
    compiled_file = gr_utils.compile(shelldir,
  File "/app/lib/python3.10/site-packages/gdm_settings/gr_utils.py", line 104, in compile
    extract_default_theme(temp_theme_dir)
  File "/app/lib/python3.10/site-packages/gdm_settings/gr_utils.py", line 70, in extract_default_theme
    resource_list = getstdout(["gresource", "list", env.HOST_ROOT + gresource_file]).decode().splitlines()
TypeError: can only concatenate str (not "NoneType") to str

### Expected behavior

Having pressed the "Apply" button and leaving it for several minutes the system used to apply the new settings.

### To Reproduce

Change any parameter and press the "Apply" button

### Application Version

2.0

### Format/Source

Flatpak and AppImage

### Environment

Manjaro  Rolling Build Kernal 5.15.85-1 LTS
GNOME 43.2

**Comment by realmazharhussain** [comment]
What output is printed on the terminal when you run the app with `-v` option?

**Comment by MrPestle** [comment]
Mazhar - the output with -v is not much different
flatpak run io.github.realmazharhussain.GdmSettings -v
INFO: Application Version    = 2.0
INFO: Operating System       = Manjaro Linux
INFO: PackageType            = Flatpak
INFO: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO: UbuntuGdmGresourceFile = None
INFO: pkexec version 122
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/gdm_settings/utils.py", line 131, in <lambda>
    finish_callback = lambda self, task, nothing: self.finish_callback()
  File "/app/lib/python3.10/site-packages/gdm_settings/window.py", line 135, in on_apply_finished
    if self.apply_task.finish():
  File "/app/lib/python3.10/site-packages/gdm_settings/utils.py", line 156, in finish
    raise value
  File "/app/lib/python3.10/site-packages/gdm_settings/utils.py", line 141, in _thread_cb
    retval = self.function()
  File "/app/lib/python3.10/site-packages/gdm_settings/settings.py", line 524, in apply_settings
    self.apply_shell_theme_settings()
  File "/app/lib/python3.10/site-packages/gdm_settings/settings.py", line 340, in apply_shell_theme_settings
    compiled_file = gr_utils.compile(shelldir,
  File "/app/lib/python3.10/site-packages/gdm_settings/gr_utils.py", line 104, in compile
    extract_default_theme(temp_theme_dir)
  File "/app/lib/python3.10/site-packages/gdm_settings/gr_utils.py", line 70, in extract_default_theme
    resource_list = getstdout(["gresource", "list", env.HOST_ROOT + gresource_file]).decode().splitlines()
TypeError: can only concatenate str (not "NoneType") to str

**Comment by realmazharhussain** [comment]
Does reinstalling `gnome-shell` package fix the issue?

**Comment by MrPestle** [comment]
Thank you - reinstalling gnome-shell enabled me to apply changed settings. I then get the issue that once I have pressed "Apply" the system appears to hang and after an hour I dropped to the CLI (CTRL+ALT+F3) and "sudo reboot now" to get back into the GUI and login.

**Comment by realmazharhussain** [comment]
> once I have pressed "Apply" the system appears to hang

This is a different problem which was previously being discussed in issue #64.

If you are interested in helping solve that problem, you can either comment there or submit a new bug report.

**Comment by MrPestle** [comment]
Thanks
Andy
