### ISSUE TITLE
fails to run

### ISSUE THREAD

**Issue by xpseudonym** [realmazharhussain/gdm-settings#148]
### What happened?

1/ Installed from flathub graphically
2/ Attempted to run - nothing happened
3/ Attempted to run from terminal:
```
$ flatpak run io.github.realmazharhussain.GdmSettings
Traceback (most recent call last):
  File "/app/bin/gdm-settings", line 27, in <module>
    from gdm_settings import Application
  File "/app/lib/python3.10/site-packages/gdm_settings/__init__.py", line 1, in <module>
    from .app import Application
  File "/app/lib/python3.10/site-packages/gdm_settings/app.py", line 12, in <module>
    from .utils import BackgroundTask
  File "/app/lib/python3.10/site-packages/gdm_settings/utils.py", line 4, in <module>
    from . import env
  File "/app/lib/python3.10/site-packages/gdm_settings/env.py", line 95, in <module>
    os_release = read_os_release()
  File "/app/lib/python3.10/site-packages/gdm_settings/env.py", line 29, in read_os_release
    val = ast.literal_eval(val)
  File "/usr/lib/python3.10/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/usr/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    "https://puri.sm/faq/
    ^
SyntaxError: unterminated string literal (detected at line 1)
$
```

### Expected behavior

runs

### To Reproduce

1/ install via flatpak
2/ run

### Detailed Explanation (Optional)

Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

### Application Version

2.1

### Format/Source

Flatpak

### Environment

- **OS**: 
gnu/linux (PureOS - Debian derivative)
`Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux`
- **GNOME**: 
3.38.5

**Comment by realmazharhussain** [comment]
Your system's `/etc/os-release` file is broken. You should report it to your distro.

In the meantime, if you do not know how to fix the file, you can upload its contents here and I'll help you fix it temporarily (it will be rewritten upon upgrade).

**Comment by xpseudonym** [comment]
Thanks for the reply and soz for the slow response.
Here's `/etc/os-release`:
```
ID=pureos
NAME=PureOS
PRETTY_NAME=PureOS

VERSION_ID=10.0
VERSION_CODENAME=byzantium

HOME_URL="https://pureos.net/"
SUPPORT_URL="https://puri.sm/faq/#faq-WherecanIfindoutmoreaboutPureOS"
BUG_REPORT_URL="https://tracker.pureos.net/"

LOGO=pureos-logo-icon
```
How is it broken?

**Comment by realmazharhussain** [comment]
> How is it broken?

Sorry! The error only showed `"https://puri.sm/faq/`. So, I thought the second `"` was not present in the file.

Now that you've provided the contents of the file, I understand that `#` in `SUPPORT_URL="https://puri.sm/faq/#faq-WherecanIfindoutmoreaboutPureOS"` is being considered as the start of a comment and the rest of the line (including the ending `"`) is ignored. Hence, causing the Exception to be raised.

I'll try and fix that soon.

**Comment by xpseudonym** [comment]
Well, I'm just blindly following direction - and, I read the # as a comment rather than a hashtag and actually went looking for the faq which I couldn't really see as very relevant...  Now that I've included the hashtag, it does make more sense...!

**Comment by xpseudonym** [comment]
Thanks @realmazharhussain  - that zip worked fine (though, ot, I found it a bit confusing that it wasn't named `gdm-settings` in gnome once installed).
