### ISSUE TITLE
Not Starting in nixos with Gnome 45

### ISSUE THREAD

**Issue by philippcou** [realmazharhussain/gdm-settings#234]
### What happened?

When I run flatpak run io.github.realmazharhussain.GdmSettings the app doesn't start. I get the following error message:

Traceback (most recent call last):
  File "/app/bin/gdm-settings", line 12, in <module>
    status = gdms.main()
             ^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gdms/__init__.py", line 86, in main
    from .gui import GdmSettingsApp
  File "/app/lib/python3.11/site-packages/gdms/gui/__init__.py", line 18, in <module>
    from gdms import debug_info
  File "/app/lib/python3.11/site-packages/gdms/debug_info.py", line 14, in <module>
    ("Default GResource File", gresource.get_default()),
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gdms/gresource.py", line 57, in get_default
    if is_unmodified(file):
       ^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gdms/gresource.py", line 41, in is_unmodified
    if env.HOST_ROOT and not gresourceFile.startswith(env.HOST_ROOT):
                             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'

### Expected behavior

App should launch

### To Reproduce

start the app

### Application Version

4.3

### Format/Source

Flatpak

### Environment

- **OS**: Nixos 24.05
- **GNOME**: 45.5

**Comment by doronbehar** [comment]
I too tried to run it on NixOS ([here's my Nixpkgs branch](https://github.com/doronbehar/nixpkgs/pull/new/WIP/gdm-settings)) and encountered the following error (similar):

```
Traceback (most recent call last):
  File "/nix/store/6j6sqakzzc2ksv233b18ay7nxb7d36g4-gdm-settings-4.4/bin/.gdm-settings-wrapped", line 13, in <module>
    status = gdms.main()
             ^^^^^^^^^^^
  File "/nix/store/6j6sqakzzc2ksv233b18ay7nxb7d36g4-gdm-settings-4.4/lib/python3.12/site-packages/gdms/__init__.py", line 86, in main
    from .gui import GdmSettingsApp
  File "/nix/store/6j6sqakzzc2ksv233b18ay7nxb7d36g4-gdm-settings-4.4/lib/python3.12/site-packages/gdms/gui/__init__.py", line 18, in <module>
    from gdms import debug_info
  File "/nix/store/6j6sqakzzc2ksv233b18ay7nxb7d36g4-gdm-settings-4.4/lib/python3.12/site-packages/gdms/debug_info.py", line 14, in <module>
    ("Default GResource File", gresource.get_default()),
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6j6sqakzzc2ksv233b18ay7nxb7d36g4-gdm-settings-4.4/lib/python3.12/site-packages/gdms/gresource.py", line 57, in get_default
    if is_unmodified(file):
       ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6j6sqakzzc2ksv233b18ay7nxb7d36g4-gdm-settings-4.4/lib/python3.12/site-packages/gdms/gresource.py", line 46, in is_unmodified
    if (os.path.exists(gresourceFile) and
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by getchoo** [comment]
Looks like this is due to NixOS straying from the standard FHS and not really an upstream issue. The `HOST_DATA_DIRS` variable [used](https://github.com/gdm-settings/gdm-settings/blob/8952843fd905005dfe68b86b417532fb0dfce6f2/gdms/gresource.py#L18-L23) to find the gresource files is set to `/usr/local/share:/usr/share` by [default](https://github.com/gdm-settings/gdm-settings/blob/8952843fd905005dfe68b86b417532fb0dfce6f2/gdms/env.py#L89), which won't exist on NixOS, let alone have anything useful

This can be worked around by setting `HOST_DATA_DIRS` manually to `/run/current-system/sw/share` in Flatpak -- it will also be present in the nixpkgs build of this with https://github.com/NixOS/nixpkgs/pull/335233

**Comment by doronbehar** [comment]
Thanks @getchoo for tracking this issue ! Indeed this can be closed now.
