### ISSUE TITLE
[BUG]  failed to start when installing from AUR

### ISSUE THREAD

**Issue by alfajet** [realmazharhussain/gdm-settings#27]
### What happened?

After installing from AUR, gdm-settings fails to install with the following error:

```
gdm-settings              

(gdm-settings:49406): Adwaita-WARNING **: 09:02:12.109: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 68, in on_activate
    self.get_widgets()
  File "/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 272, in get_widgets
    self.builder.add_from_file(file)
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/s/usr/share/gdm-settings/main-window.ui”: No such file or directory (4)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 82, in on_shutdown
    self.save_window_state()
  File "/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 540, in save_window_state
    width, height = widgets.main_window.get_default_size()
AttributeError: 'WidgetContainer' object has no attribute 'main_window'
```

It looks like the following line in the stack trace is relevant:

```
  File "/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 272, in get_widgets
    self.builder.add_from_file(file)
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/s/usr/share/gdm-settings/main-window.ui”: No such file or 
```

Somehow the path to the `main-window.ui` file is badly constructed.

Note: I confirm that the dependencies have been correctly installed:

```
$ pikaur -S libadwaita glib2 python-gobject gettext
[sudo] password for alex: 
Reading repository package databases...
Reading local package database...

:: Repository packages will be installed:
 gettext                       0.21-2       -> 0.21-2
 glib2                         2.72.0-1     -> 2.72.0-1
 libadwaita                    1:1.1.0-1    -> 1:1.1.0-1
 python-gobject                3.42.0-3     -> 3.42.0-3
```

### Expected behavior

Running gdm-settings works

### To Reproduce

Install from AUR on a fresh arch OS, with latest gnome version.

### Application Version

latest development version

### Source

Arch User Repository

### Environment

```markdown
- **OS**: arch linux
- **GNOME**: 42
```

**Comment by realmazharhussain** [comment]
Can you tell me exactly what version of the app is installed on your system? You can find it out by running the command `pacman -Q gdm-settings`.

**Comment by alfajet** [comment]
Here is what I've got:

```
$ pacman -Q gdm-settings           
gdm-settings-git 1:0.4+50+gc3fbf31-1
```

**Comment by realmazharhussain** [comment]
There have been 17 commits since that version. Plz, update to the latest version and check if that works. If it doesn't work, inform me and I'll start digging. Even if it works, I'd like you inform me about it.

**Comment by alfajet** [comment]
I updated the package and still eperience the same issue:

```
$ pacman -Q gdm-settings      
gdm-settings-git 1:0.4+67+g4a18211-1
```

```
$ gdm-settings          

(gdm-settings:129205): Adwaita-WARNING **: 10:51:52.889: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 71, in on_activate
    self.get_widgets()
  File "/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 275, in get_widgets
    self.builder.add_from_file(file)
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/s/usr/share/gdm-settings/main-window.ui”: No such file or directory (4)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 85, in on_shutdown
    self.save_window_state()
  File "/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 546, in save_window_state
    width, height = widgets.main_window.get_default_size()
AttributeError: 'WidgetContainer' object has no attribute 'main_window'
```

I'll try to completely uninstall it and re-install it to see if that makes a difference. Not sure why the `main-window.ui` path is prefixed with `/s/`.

**Comment by alfajet** [comment]
Still the same outcome.

**Comment by alfajet** [comment]
If that helps, here is my generated `info.py` file:

```python
from sys import argv
from os  import path

build_type = 'plain'
application_name = _("Login Manager Settings")
project_name = 'gdm-settings'
version = '0.5.alpha'
application_id = 'io.github.realmazharhussain.GdmSettings'

prefix = '/usr'
bin_dir = 'bin'
data_dir = '/usr/share'
py_modules_dir = '/usr/lib/python3.10/site-packages/'
py_module_name = 'gdm_settings'

dest_dir = path.dirname(argv[0]).split(bin_dir)[0].replace(prefix,'')
ui_dir = path.join(dest_dir, data_dir.strip('/'), project_name.strip('/'))
```

**Comment by realmazharhussain** [comment]
Add the following lines at the end of `/usr/lib/python3.10/site-packages/gdm_settings/info.py`

```python
print('dest_dir:', dest_dir)
print('ui_dir:', ui_dir)
```

and then run `gdm-settings` and provide its output here.

**Comment by alfajet** [comment]
```$  gdm-settings                                                   
argv[0]: /usr/sbin/gdm-settings
dest_dir: /s
ui_dir: /s/usr/share/gdm-settings
```

**Comment by alfajet** [comment]
All right, it works when I specifically run `/usr/bin/gdm-settings`

**Comment by realmazharhussain** [comment]
Thank you for taking the time to help me debug the issue. I'll be fixing that as soon as I can.

**Comment by realmazharhussain** [comment]
I have fixed the issue. Update to the latest version and see if it works now. And don't forget to report back.

**Comment by alfajet** [comment]
Hi, I have downloaded the latest version and I confirm that the issue has been resolved for me. Many thanks for your reactivity, and best wishes for your project. :)

**Comment by realmazharhussain** [comment]
You are welcome and thanks.
