### ISSUE TITLE
[BUG] UnicodeDecodeError can't apply settings.

### ISSUE THREAD

**Issue by j1cs** [realmazharhussain/gdm-settings#35]
### What happened?

Just installed gdm-settings-git from aur and gave me this error after hit the apply button
```sh
(gdm-settings:20965): Gtk-WARNING **: 01:30:27.493: Theme parser error: gtk.css:5347:3-19: No property named "-gtk-icon-effect"
saving default theme ...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 95, in on_apply
    if self.settings.apply_settings():
  File "/usr/lib/python3.10/site-packages/gdm_settings/settings_manager.py", line 657, in apply_settings
    self.apply_gresource_settings()
  File "/usr/lib/python3.10/site-packages/gdm_settings/settings_manager.py", line 555, in apply_gresource_settings
    gresource_utils.auto_backup()
  File "/usr/lib/python3.10/site-packages/gdm_settings/settings_manager.py", line 253, in auto_backup
    self._extract_default_pure_theme()
  File "/usr/lib/python3.10/site-packages/gdm_settings/settings_manager.py", line 240, in _extract_default_pure_theme
    self.extract_default_theme(target_dir=TEMP_DIR, name='default-pure')
  File "/usr/lib/python3.10/site-packages/gdm_settings/settings_manager.py", line 218, in extract_default_theme
    source_shell_dir = self.extract_theme(gresource_file=self.get_default())
  File "/usr/lib/python3.10/site-packages/gdm_settings/settings_manager.py", line 205, in extract_theme
    content = getoutput(f"gresource extract {gresource_file} {resource}")
  File "/usr/lib/python3.10/subprocess.py", line 643, in getoutput
    return getstatusoutput(cmd)[1]
  File "/usr/lib/python3.10/subprocess.py", line 624, in getstatusoutput
    data = check_output(cmd, shell=True, text=True, stderr=STDOUT)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1136, in communicate
    stdout = self.stdout.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

### Expected behavior

```markdown
Apply changes without error.
```

### To Reproduce

```markdown
Using yay:


$ yay -S gdm-settings-git
...
$ gdm-settings
...
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

### Application Version

 v0.5

### Source

AUR

### Environment

```markdown
- **OS**: EndeavourOS
- **GNOME**: 42.0
```

**Comment by realmazharhussain** [comment]
Just fixed. Update the app and run again.

**Comment by realmazharhussain** [comment]
And don't forget to report back.

**Comment by j1cs** [comment]
Great! worked fine. Thank you.
