### ISSUE TITLE
[BUG] Changes has no effect [PopOS 22.04]

### ISSUE THREAD

**Issue by squalou** [realmazharhussain/gdm-settings#43]
### What happened?

Changes in application have no effect on GDM

### Expected behavior

changes applied

### To Reproduce

open the app, do some changes, hit apply

### Detailed Explanation (Optional)

I run the application installed from flatpak.
I change for instance the login background.
Clicking Apply, reboot, no effect.

When running flatpak verbose, I can get following output when hitting 'Apply'

(tehre are similar errors when trying 

```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gdm_settings/gdm_settings_gui.py", line 95, in on_apply
    if self.settings.apply_settings():
  File "/app/lib/python3.9/site-packages/gdm_settings/settings_manager.py", line 658, in apply_settings
    self.apply_gresource_settings()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings_manager.py", line 556, in apply_gresource_settings
    gresource_utils.auto_backup()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings_manager.py", line 254, in auto_backup
    self._extract_default_pure_theme()
  File "/app/lib/python3.9/site-packages/gdm_settings/settings_manager.py", line 241, in _extract_default_pure_theme
    self.extract_default_theme(target_dir=TEMP_DIR, name='default-pure')
  File "/app/lib/python3.9/site-packages/gdm_settings/settings_manager.py", line 230, in extract_default_theme
    copytree(source_shell_dir, target_shell_dir)
  File "/usr/lib/python3.9/shutil.py", line 564, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/<my_username>/.var/app/io.github.realmazharhussain.GdmSettings/cache/gdm-settings/extracted'
```

I did try "extract shell theme" and got a similar issue

```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gdm_settings/gdm_settings_gui.py", line 140, in on_extract_shell_theme
    if settings_manager.gresource_utils.extract_default_theme(additional_css=additional_css):
  File "/app/lib/python3.9/site-packages/gdm_settings/settings_manager.py", line 223, in extract_default_theme
    with open(source_shell_dir + "/gnome-shell.css", "a") as shell_css:
FileNotFoundError: [Errno 2] No such file or directory: '/home/<my_username>/.var/app/io.github.realmazharhussain.GdmSettings/cache/gdm-settings/extracted/gnome-shell.css'


```

### Application Version

0.5.2

### Source

Flatpak

### Environment

- **OS**: popOS 22.04
- **GNOME**: 42

**Comment by rob83gh** [comment]
I'm seeing the same error on Ubuntu 22.04, version 0.5.2, installed from flathub.

**Comment by lallenlowe** [comment]
I'm seeing the same issue on Fedora 36. Version 0.5.2 flatpak from flathub. Changes have no effect.

**Comment by Pixtriks** [comment]
Same issue here with Pop_OS 22.04 and installed from flathub. Version 0.5.2
