### ISSUE TITLE
Error runing

### ISSUE THREAD

**Issue by AnonymousWebHacker** [realmazharhussain/gdm-settings#5]
```
 gdm-settings 
Traceback (most recent call last):
  File "/usr/local/bin/gdm-settings", line 384, in on_activate
    get_widgets()
  File "/usr/local/bin/gdm-settings", line 31, in get_widgets
    widgets.builder.add_from_file(main_window_ui_file)
gi.repository.GLib.Error: gtk-builder-error-quark: /usr/local/share/gdm-settings/ui/main-window.ui:44:1 Invalid object type 'AdwToastOverlay' (6)
Traceback (most recent call last):
  File "/usr/local/bin/gdm-settings", line 459, in on_shutdown
    save_window_state()
  File "/usr/local/bin/gdm-settings", line 148, in save_window_state
    width, height = widgets.main_window.get_default_size()
AttributeError: 'WidgetContainer' object has no attribute 'main_window'
```

**Comment by realmazharhussain** [comment]
Is LibAdwaita installed on your system?

**Comment by AnonymousWebHacker** [comment]
I add add libadwaita.list 
`deb http://cz.archive.ubuntu.com/ubuntu jammy main universe`
 and installed `sudo apt install  libadwaita-1-0`

```
/etc/apt/sources.list.d$ meson build
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 293, in run
    app = MesonApp(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 76, in __init__
    (self.source_dir, self.build_dir) = self.validate_dirs(options.builddir,
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 160, in validate_dirs
    (src_dir, build_dir) = self.validate_core_dirs(dir1, dir2)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 131, in validate_core_dirs
    os.makedirs(ndir1)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/etc/apt/sources.list.d/build'

```

**Comment by calcastor** [comment]
If you have libadwaita installed, it is likely not up to date with upstream. Fedora 35 in particular lacks libadwaita 1.0.x as its version of gtk4 is older than the version required to build the first release of libadwaita.

**Comment by AnonymousWebHacker** [comment]
> If you have libadwaita installed, it is likely not up to date with upstream. Fedora 35 in particular lacks libadwaita 1.0.x stable as its version of gtk4 is older than the version required to build the first release of libadwaita.

I am using Ubuntu, `libadwaita` isn't on repos

**Comment by Kryptos-123** [comment]
As a temporary workaround, you can make an appimage using `make_appimage.sh` and use that. You'll need to have `appimagetool` installed.

**Comment by AnonymousWebHacker** [comment]
```
jose@Latitude-E6430:~/Aplications$ ./Login_Manager_Settings-nodeps.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_Login_vy8kNN/usr/bin/gdm-settings", line 2, in <module>
    from gdm_settings import gdm_settings_gui
  File "/tmp/.mount_Login_vy8kNN/usr/lib/python3.10/site-packages/gdm_settings/gdm_settings_gui.py", line 5, in <module>
    gi.require_version("Adw", '1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Adw not available

```
Tanks guys

**Comment by realmazharhussain** [comment]
Sorry, for the inconvenience.

The app now has a real AppImage which should work just fine. Visit https://github.com/realmazharhussain/gdm-settings/releases to download it.

The app also has a Flatpak on the Flathub now.
