### ISSUE TITLE
ModuleNotFoundError: No module named 'gdm_settings'

### ISSUE THREAD

**Issue by nestormarius** [realmazharhussain/gdm-settings#6]
Hello. The program won't start after manual installation on Fedora 36 (pre-release).

```
gdm-settings 
Traceback (most recent call last):
  File "/usr/local/bin/gdm-settings", line 2, in <module>
    from gdm_settings import gdm_settings_gui
ModuleNotFoundError: No module named 'gdm_settings'
```

**Comment by realmazharhussain** [comment]
Thank you for reporting the issue. I will be working on it as soon as possible. For now, the workaround is to run the following commands to install it

```bash
rm -rf build
meson build --prefix=/usr
meson install -C build
```

**Comment by nestormarius** [comment]
Now I get this error when running meson install -C build...

```
 meson install -C build
ninja: Entering directory `/home/marius/Downloads/gdm-settings/build'
[1/9] Generating 'src/blueprints/gdm-settings.p/appearance-page.ui'.
FAILED: src/blueprints/gdm-settings.p/appearance-page.ui 
/usr/local/bin/blueprint-compiler compile ../src/blueprints/appearance-page.blp --output src/blueprints/gdm-settings.p/appearance-page.ui
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-compiler", line 22, in <module>
    from blueprintcompiler import main
ModuleNotFoundError: No module named 'blueprintcompiler'
[2/9] Generating 'src/blueprints/gdm-settings.p/sound-page.ui'.
FAILED: src/blueprints/gdm-settings.p/sound-page.ui 
/usr/local/bin/blueprint-compiler compile ../src/blueprints/sound-page.blp --output src/blueprints/gdm-settings.p/sound-page.ui
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-compiler", line 22, in <module>
    from blueprintcompiler import main
ModuleNotFoundError: No module named 'blueprintcompiler'
[3/9] Generating 'src/blueprints/gdm-settings.p/night-light-page.ui'.
FAILED: src/blueprints/gdm-settings.p/night-light-page.ui 
/usr/local/bin/blueprint-compiler compile ../src/blueprints/night-light-page.blp --output src/blueprints/gdm-settings.p/night-light-page.ui
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-compiler", line 22, in <module>
    from blueprintcompiler import main
ModuleNotFoundError: No module named 'blueprintcompiler'
[4/9] Generating 'src/blueprints/gdm-settings.p/misc-page.ui'.
FAILED: src/blueprints/gdm-settings.p/misc-page.ui 
/usr/local/bin/blueprint-compiler compile ../src/blueprints/misc-page.blp --output src/blueprints/gdm-settings.p/misc-page.ui
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-compiler", line 22, in <module>
    from blueprintcompiler import main
ModuleNotFoundError: No module named 'blueprintcompiler'
[5/9] Generating 'src/blueprints/gdm-settings.p/top-bar-page.ui'.
FAILED: src/blueprints/gdm-settings.p/top-bar-page.ui 
/usr/local/bin/blueprint-compiler compile ../src/blueprints/top-bar-page.blp --output src/blueprints/gdm-settings.p/top-bar-page.ui
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-compiler", line 22, in <module>
    from blueprintcompiler import main
ModuleNotFoundError: No module named 'blueprintcompiler'
[6/9] Generating 'src/blueprints/gdm-settings.p/main-window.ui'.
FAILED: src/blueprints/gdm-settings.p/main-window.ui 
/usr/local/bin/blueprint-compiler compile src/blueprints/main-window.blp --output src/blueprints/gdm-settings.p/main-window.ui
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-compiler", line 22, in <module>
    from blueprintcompiler import main
ModuleNotFoundError: No module named 'blueprintcompiler'
[7/9] Generating 'src/blueprints/gdm-settings.p/fonts-page.ui'.
FAILED: src/blueprints/gdm-settings.p/fonts-page.ui 
/usr/local/bin/blueprint-compiler compile ../src/blueprints/fonts-page.blp --output src/blueprints/gdm-settings.p/fonts-page.ui
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-compiler", line 22, in <module>
    from blueprintcompiler import main
ModuleNotFoundError: No module named 'blueprintcompiler'
[8/9] Generating 'src/blueprints/gdm-settings.p/touchpad-page.ui'.
FAILED: src/blueprints/gdm-settings.p/touchpad-page.ui 
/usr/local/bin/blueprint-compiler compile ../src/blueprints/touchpad-page.blp --output src/blueprints/gdm-settings.p/touchpad-page.ui
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-compiler", line 22, in <module>
    from blueprintcompiler import main
ModuleNotFoundError: No module named 'blueprintcompiler'
ninja: build stopped: subcommand failed.
Could not rebuild /home/marius/Downloads/gdm-settings/build
```

**Comment by realmazharhussain** [comment]
It is a problem with blueprint-compiler. You can just uninstall it with following commands

```bash
sudo rm /usr/local/bin/blueprint-compiler
sudo rm /usr/local/lib/pkgconfig/blueprint-compiler.pc
sudo rm -rf /usr/local/lib/python3.10/site-packages/blueprintcompiler
```

After that, you can leave it uninstalled **OR** re-install it with the same commands mentioned in my previous comment; that is

```shell
rm -rf build
meson build --prefix=/usr
meson install -C build
```

**Comment by nestormarius** [comment]
Ok, thanks. Removing blueprint-compiler with the sudo rm /usr/local/bin/blueprint-compiler command did the job. I was able to rebuild the program and install it without issues. However, now I get this error when attempting to run it...

```
gdm-settings 

(gdm-settings:76276): Gtk-WARNING **: 08:45:51.633: Theme directory 32@2x/devices of theme Vimix-dark has no size field


(gdm-settings:76276): GLib-GIO-ERROR **: 08:45:51.734: Settings schema 'io.github.realmazharhussain.GdmSettings' is not installed
Trace/breakpoint trap (core dumped)

```

**Comment by realmazharhussain** [comment]
> (gdm-settings:76276): Gtk-WARNING **: 08:45:51.633: Theme directory 32@2x/devices of theme Vimix-dark has no size field

is a problem with your icon theme

> (gdm-settings:76276): GLib-GIO-ERROR **: 08:45:51.734: Settings schema 'io.github.realmazharhussain.GdmSettings' is not installed
Trace/breakpoint trap (core dumped)

has been fixed

**Comment by realmazharhussain** [comment]
> ModuleNotFoundError: No module named 'gdm_settings'

has been fixed
