### ISSUE TITLE
Settings modification not taken into account

### ISSUE THREAD

**Issue by iscandarster** [realmazharhussain/gdm-settings#84]
### What happened?

When modifying settings, hitting Apply button, closing Appimage and rebooting the settings are still the same as not modified.

For example (settings tested):
Miscellaneous/Disable User List set to ON
Miscellaneous/Enable Log set to OFF
Miscellaneous/Welcome Message set to "TEST"
Appearance/Background/Type set to Color/Yellow Color
Appearance/Background/Type set to Image/JPEG Image

These have been tested not working.

### Expected behavior

Change the setting according to choice

### To Reproduce

Launch the Login Manager Settings.Appimage 
Change the settings 
Apply 
Reboot

### Application Version

gdm-settings v0.6.1

### Source

Login_Manager_Settings-nodeps.AppImage

### Environment

- OS: Ubuntu 22.04 LTS
- GNOME: 42.2
- gdm3

**Comment by realmazharhussain** [comment]
Run it inside the terminal with `-v` option and hit Apply. Then post its output here.

Also, when you hit apply, does the in-app notification say that it succeeded or failed?

**Comment by iscandarster** [comment]
> Run it inside the terminal with `-v` option and hit Apply. Then post its output here.
> 
> Also, when you hit apply, does the in-app notification say that it succeeded or failed?

```
$ ./gdm-settings.AppImage -v 
INFO: Operating System       = Ubuntu 22.04 LTS
INFO: PackageType            = AppImage
INFO: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO: UbuntuGdmGresourceFile = /usr/share/gnome-shell/gdm-theme.gresource
INFO: TEMP_DIR               = /home/alex/.cache/gdm-settings
INFO: SYSTEM_DATA_DIRS       = /usr/local/share:/usr/share
INFO: GDM 42.0
INFO: pkexec version 0.105
```
HITTING THE APPLY BUTTON (NO MESSAGE IN THE APP, NEITHER SUCCEEDED OR FAILED)

```
Traceback (most recent call last):
  File "/tmp/.mount_gdm-sezkbUFO/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 248, in on_apply
    if self.settings.apply_settings():
  File "/tmp/.mount_gdm-sezkbUFO/usr/lib/python3.10/site-packages/gdm_settings/settings.py", line 409, in apply_settings
    self.apply_shell_theme_settings()
  File "/tmp/.mount_gdm-sezkbUFO/usr/lib/python3.10/site-packages/gdm_settings/settings.py", line 302, in apply_shell_theme_settings
    compiled_file = gr_utils.compile(shelldir,
  File "/tmp/.mount_gdm-sezkbUFO/usr/lib/python3.10/site-packages/gdm_settings/gr_utils.py", line 147, in compile
    run(['glib-compile-resources',
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'glib-compile-resources'
```
KEYBOARD INTERRUPT

```
^CTraceback (most recent call last):
  File "/tmp/.mount_gdm-sezkbUFO/usr/bin/gdm-settings", line 24, in <module>
    return_value = app.run(sys.argv)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gio.py", line 40, in run
    with register_sigint_fallback(self.quit):
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt

$
```

**Comment by realmazharhussain** [comment]
It seems like a dependency `GLib` (package name: `libglib2.0-dev`) is missing.

I will be fixing this error so that it shows a graphical dialog telling the user about the situation instead of erroring out.

In the meantime, just install package `libglib2.0-dev` and the app should start working.

**Comment by iscandarster** [comment]
I installed libglib2.0-dev and it's dependencies throw Synaptic and it worked like a charm ... nut only once !

I set:
Disable User List to ON, 
Startup Logo OFF  
set a Welcome Message
and maybe a login background image.

It worked but the second time I wanted to relaunched it to change the Welcome Message and it didn't launched ! 

```
$ ./gdm-settings1.AppImage -v
INFO: Operating System       = Ubuntu 22.04.1 LTS
INFO: PackageType            = AppImage
Traceback (most recent call last):
  File "/tmp/.mount_gdm-se7XMHd1/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 72, in on_activate
    self.initialize_settings()
  File "/tmp/.mount_gdm-se7XMHd1/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 349, in initialize_settings
    from .settings import Settings
  File "/tmp/.mount_gdm-se7XMHd1/usr/lib/python3.10/site-packages/gdm_settings/settings.py", line 7, in <module>
    from . import gr_utils
  File "/tmp/.mount_gdm-se7XMHd1/usr/lib/python3.10/site-packages/gdm_settings/gr_utils.py", line 24, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
Traceback (most recent call last):
  File "/tmp/.mount_gdm-se7XMHd1/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 118, in on_shutdown
    self.save_window_state()
  File "/tmp/.mount_gdm-se7XMHd1/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 693, in save_window_state
    width, height = widgets.main_window.get_default_size()
AttributeError: 'types.SimpleNamespace' object has no attribute 'main_window'
$ 

```

Now it's not working at all

**Comment by realmazharhussain** [comment]
The error mentioned in [above comment](https://github.com/realmazharhussain/gdm-settings/issues/84#issuecomment-1200382297) has been fixed in the latest source code.
